# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_park', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_details',
            name='comment_email_id',
            field=models.CharField(max_length=250),
        ),
    ]
