# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import water_park.fields
import water_park.validators


class Migration(migrations.Migration):

    dependencies = [
        ('water_park', '0003_auto_20190201_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_details',
            name='comment_email_id',
            field=models.CharField(max_length=250, validators=[water_park.validators.validate_domainonly_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=water_park.fields.PhoneNumberField(max_length=5, unique=True),
        ),
    ]
