# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import water_park.validators


class Migration(migrations.Migration):

    dependencies = [
        ('water_park', '0004_auto_20190201_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_details',
            name='comment_email_id',
            field=models.EmailField(max_length=250, validators=[water_park.validators.validate_domainonly_email]),
        ),
    ]
