# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-06 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_park', '0006_auto_20190206_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(max_length=10),
        ),
    ]
