# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-18 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import water_park.validators


class Migration(migrations.Migration):

    dependencies = [
        ('water_park', '0007_auto_20190206_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='park_details',
            name='park_docs',
            field=models.FileField(default='Docs/None/new-doc', upload_to='Docs/'),
        ),
        migrations.AlterField(
            model_name='park_details',
            name='park_logo',
            field=models.ImageField(default='Images/None/new-img.jpg', upload_to='Images/', validators=[water_park.validators.validate_image_ext]),
        ),
    ]
