# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_park', '0008_auto_20190418_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park_details',
            name='park_url',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
