# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import water_park.validators


class Migration(migrations.Migration):

    dependencies = [
        ('water_park', '0010_auto_20190501_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[water_park.validators.validate_integers]),
        ),
    ]
